name: configr
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  i3config: ^1.1.1
  path: ^1.9.1
  crypto: ^3.0.6
  file: ^7.0.1
  mustache_template: ^2.0.0
  xdg_desktop_portal: ^0.1.12
  logging: ^1.3.0
  interact: ^2.2.0
  opentelemetry: ^0.18.6
  app_dirs: ^0.2.0
  liquify: ^0.8.1
  archive: ^4.0.2
  http:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  mockito: ^5.4.4
  build_runner: ^2.0.0

dependency_overrides:
  intl: ^0.20.1

executables:
  configr: main
