// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'getting-started/overview'},
      items: [
        'getting-started/tutorial',
        'getting-started/cli-usage',
        'getting-started/migration-guide',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/architecture',
        'guides/remote-execution',
        'guides/multi-host',
        'guides/ssh-vm-guide',
        'guides/hooks',
        'guides/plugin-system',
        'guides/secrets',
        'guides/terminal-ui',
        'guides/privilege-lock',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/variables', 'reference/rollback'],
    },
    {
      type: 'category',
      label: 'Action Blocks',
      items: [
        'blocks/alternatives-module',
        'blocks/assert-module',
        'blocks/authorized_key',
        'blocks/backup',
        'blocks/blockinfile-module',
        'blocks/compress',
        'blocks/copy',
        'blocks/cron',
        'blocks/debug',
        'blocks/decompress',
        'blocks/delete',
        'blocks/download',
        'blocks/echo',
        'blocks/execute',
        'blocks/fail',
        'blocks/fetch',
        'blocks/file',
        'blocks/file-module',
        'blocks/firewalld',
        'blocks/gather_facts',
        'blocks/git',
        'blocks/group-module',
        'blocks/hostname-module',
        'blocks/known_hosts',
        'blocks/lineinfile-module',
        'blocks/locale_gen-module',
        'blocks/mount',
        'blocks/move',
        'blocks/network',
        'blocks/package',
        'blocks/pause',
        'blocks/permissions',
        'blocks/raw',
        'blocks/rename',
        'blocks/replace-module',
        'blocks/script',
        'blocks/service',
        'blocks/set_fact',
        'blocks/slurp',
        'blocks/stat',
        'blocks/symlink',
        'blocks/sync',
        'blocks/sysctl-module',
        'blocks/systemd',
        'blocks/template',
        'blocks/timezone-module',
        'blocks/touch',
        'blocks/ufw',
        'blocks/unarchive',
        'blocks/uri',
        'blocks/user-module',
        'blocks/validate',
        'blocks/wait_for',
      ],
    },
  ],
};

module.exports = sidebars;
